import SEOHead from "@/components/SEOHead";

const Terms = () => (
  <div className="page-container max-w-2xl mx-auto animate-fade-up">
    <SEOHead
      title="Terms & Conditions - Online Calculators"
      description="Read the Terms & Conditions for using Online Calculators student tools, calculators, and blog content."
      path="/terms"
    />
    <h1 className="text-2xl font-bold text-foreground mb-4">Terms &amp; Conditions</h1>
    <div className="bg-card rounded-2xl p-5 sm:p-6 border border-border space-y-4 text-[14px] text-muted-foreground leading-relaxed">
      <p><strong>Last updated:</strong> May 2026</p>

      <h2 className="text-base font-semibold text-foreground">1. Acceptance of Terms</h2>
      <p>By accessing and using Online Calculators (“we”, “our”, “the website”), you agree to be bound by these Terms &amp; Conditions. If you do not agree, please do not use the website.</p>

      <h2 className="text-base font-semibold text-foreground">2. Use of Tools</h2>
      <p>This website provides tools (attendance tracker, CGPA calculator, study planner, expense tracker, and others) for informational and educational purposes only. Results are based on user input and may not always be 100% accurate.</p>

      <h2 className="text-base font-semibold text-foreground">3. User Responsibility</h2>
      <p>Users are fully responsible for how they use the information generated by our tools. Always verify with your college, university, or a qualified person before making important academic, financial, or health decisions.</p>

      <h2 className="text-base font-semibold text-foreground">4. No Liability</h2>
      <p>Online Calculators is not liable for any direct, indirect, incidental or consequential loss arising from the use of the website, including but not limited to academic outcomes, financial decisions, or health decisions.</p>

      <h2 className="text-base font-semibold text-foreground">5. Intellectual Property</h2>
      <p>All content, branding, design and code on Online Calculators are the property of Online Calculators and protected by applicable intellectual property laws. You may not copy, redistribute, or republish our content without permission.</p>

      <h2 className="text-base font-semibold text-foreground">6. Third-Party Services</h2>
      <p>We may display ads via Google AdSense and use analytics services. These third parties may use cookies and collect anonymous usage data as described in their own policies.</p>

      <h2 className="text-base font-semibold text-foreground">7. Changes to Terms</h2>
      <p>We may update these Terms at any time. Continued use of the website after changes means you accept the updated Terms.</p>

      <h2 className="text-base font-semibold text-foreground">8. Contact</h2>
      <p>For questions about these Terms, email us at <a className="text-primary underline" href="mailto:primehrithik@gmail.com">primehrithik@gmail.com</a>.</p>
    </div>
  </div>
);

export default Terms;
