import { Download } from "lucide-react";

interface DownloadReportProps {
  getData: () => { title: string; rows: { label: string; value: string }[] };
}

const DownloadReport = ({ getData }: DownloadReportProps) => {
  const download = () => {
    const { title, rows } = getData();
    let text = `${title}\n${"=".repeat(40)}\nGenerated: ${new Date().toLocaleString()}\n\n`;
    rows.forEach(r => { text += `${r.label}: ${r.value}\n`; });
    text += `\n${"=".repeat(40)}\nGenerated by Online Calculators`;
    const blob = new Blob([text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${title.replace(/\s+/g, "_")}_Report.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <button onClick={download}
      className="w-full py-3 rounded-xl bg-accent text-accent-foreground text-base font-semibold hover:opacity-90 transition-opacity inline-flex items-center justify-center gap-2">
      <Download size={18} /> Download Report
    </button>
  );
};

export default DownloadReport;
